name: Python Pipeline

on: 
  push:
    branches: [main, dev]
  pull_request:

jobs: 
  test: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt || true
      - run: python -m unittest discover

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         name: hello
         
